// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn929NPg9ItKeyrI8Z-RnuNWzL-60p5Eg',
    appId: '1:433359928875:web:4a9b0b2aab72a0ff4a746e',
    messagingSenderId: '433359928875',
    projectId: 'ft-spending',
    authDomain: 'ft-spending.firebaseapp.com',
    storageBucket: 'ft-spending.appspot.com',
    measurementId: 'G-YB8RMHBF8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqGLXJnMoyh3MIh7auGu8M3gaBRJh034g',
    appId: '1:433359928875:android:2a16d13ae82e9cb84a746e',
    messagingSenderId: '433359928875',
    projectId: 'ft-spending',
    storageBucket: 'ft-spending.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtW63ln1B3HTfpvefrhihagapAS_0VyBk',
    appId: '1:433359928875:ios:7a0af5bae3b0016e4a746e',
    messagingSenderId: '433359928875',
    projectId: 'ft-spending',
    storageBucket: 'ft-spending.appspot.com',
    iosClientId: '433359928875-ji0101h9211iqftfi8f0lsn0hrjj72bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.ftSpending',
  );
}
